#Thank You for downloading!
#Author: AntTheAntster
#Support: https://discord.link/AntsPlugins
#Copyright AntTheAntster 2021. All Rights Reserved.
#For more copyright info, type /aa license

#Do not touch this, its for notifying config updates.
Version: 1.0

#The economy used by the plugin. Either Vault or Gems (Internal Currency, use "/aa help" in-game for more info)
Economy: Gems

#Menus Settings
Menu:
  Title: "&eAnts Artifacts"
  Close Menu:
    Icon: "BARRIER"
    Icon Title: "&cClose Menu"
  Owned Artifacts: #Menu layout/size will be the same as Shop layout/size.
    Icon: "ENDER_CHEST"
    Icon Title: "&bOwned Artifacts"
    Title: "&eOwned Artifacts"
  Shop:
    Icon: "CHEST"
    Icon Title: "&bArtifacts Shop"
    Size: 18 #9, 18, 27, 36, 45, 54 ONLY!
    Title: "&eArtifacts Shop"
    Balance Settings:
      Enabled: true #Enable or disable the item displaying the players balance?
      Balance Material: EMERALD #Item to represent the players balance (Either Gems balance or Vault balance depending on which one is selected)
      Slot: 13 #Which Slot?
      Title: "&eBalance: &a{balance}" #The title of the item ({balance} will display the players balance)
    Fill Settings:
      Fill Empty: true #Fill empty slots?
      Fill Material: "BLACK_STAINED_GLASS_PANE"

#Artifacts Settings
Artifacts:
  Strength:
    Name: "&cStrength Artifact"
    Item: "DIAMOND_SWORD"
    Slot: 0
    Price: 1000
    Effect Level: 1 #Effect Level starting from 0 (0 = Strength 1, 1 = Strength 2, 2 = Strength 3, etc)
    Lore:
      - "&ePermanent &cStrength &eEffect!"
      - "&eCost: &a1000"
  Speed:
    Name: "&cSpeed Artifact"
    Item: "DIAMOND_BOOTS"
    Slot: 1
    Price: 1000
    Effect Level: 1 #Effect Level starting from 0 (0 = Strength 1, 1 = Strength 2, 2 = Strength 3, etc)
    Lore:
      - "&ePermanent &bSpeed &eEffect!"
      - "&eCost: &a1000"


#Messages used by the plugin
View Own Gems: "&eYour Gems: &a{gems}" #  {gems} - Returns the amount of gems for the specified player.
View Others Gems: "&e{playername}'s Gems: &a{gems}" #  {playername} - Displays the target player's name.
Artifact Bought: "&eYou just bought an Artifact!"
Artifact Already Owned: "&cYou already own this artifact"
Artifact Enabled: "&aArtifact Enabled!"
Artifact Disabled: "&cArtifact Disabled!"